### PR TITLE
Add npm package of the documentation

### PR DESCRIPTION
**Pull request by w-vi**

### CODE REVIEW

**Comment by zdne** [comment]
@kylef @w-vi why are we doing this?

**Comment by pksunkara** [comment]
I agree with Z. Why are we doing this?

**Comment by kylef** [comment]
Yes, this is an approach I don't want to go down. I believe with some discussion we can proceed by using a git submodule now so I'm going to close this.

**Comment by w-vi** [comment]
It really sucks, so maybe next we will be able to persuade the rest that submodules are the best option

**Comment by zdne** [comment]
@w-vi @kylef @pksunkara I did not say this is good or bad. Rather, I was missing any explanation of this PR.

**Pull request closed without merging**
