### PR TITLE
Update 10. Data Structures.md

### PR DESCRIPTION
**Pull request by telaviv1**
Adding an example of a required parameter

### CODE REVIEW

**Comment by zdne** [comment]
Hey @telaviv1 thanks for contribution! I am definitely up for showing more of the MSON syntax in the advanced example. However these examples are trying to follow a continuity with what was in the previous installment. Here you are introducing `required` for something that was previously optional. Besides this is not a good practice in general (making something that used to be optional required) – because you are breaking the clients it may also confuse the readers who read the previous parts (no.9 and 8). 

At a minimum I would suggest to add an explanation at the top of this example. Or move it all the way to example no.8. What do you think?

**Comment by telaviv1** [comment]
Add it to example number 8.  That's definitely the right place for it.

**Comment by zdne** [comment]
@telaviv1 Makes sense. Note this needs updated of both 8, 9, and 10. Are you going to do this as a part of this PR?

**Comment by pksunkara** [comment]
@telaviv1 Will you be working on this?

**Comment by pksunkara** [comment]
Continued in #287

**Comment by zdne** [comment]
Thanks @pksunkara !

**Pull request closed without merging**
